version: "3.8"
services:
  shared-chrome:
    image: selenium/node-chrome:95.0
    shm_size: 2gb
    env_file:
      - .env
    networks:
      - ${NETWORK_NAME}
    environment:
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true      