version: "3.8"
services:
  maven:
    image: maven:3.8.3-jdk-8-slim
    container_name: maven 
    environment:
     REMOTE_URL: http://${GRID_URL_ADDRESS}:${GRID_URL_PORT}/
     REMOTE_EXECUTION: "true"
    networks:
      - default 
    volumes:
     - ./selenium-agregator:/selenium-agregator 
     - $HOME/.m3:/root/.m2  # Using your home .m2 cache directory 
     #- m2:/root/.m2        #  this way an internal docker volume m2 will be created.
    command: bash -c " sh selenium-agregator/scripts/run_calculator_test.sh"
    networks:
      - ${NETWORK_NAME}
networks:
  selenium-grid:
   name: ${NETWORK_NAME}
