version: "3.9"
services:
  selenium-event-bus:
    image: selenium/event-bus:4.0.0
    container_name: selenium-event-bus
    ports:
      - "4442:4442"
      - "4443:4443"
      - "5557:5557"
    env_file:
      - .env

  selenium-sessions:
    image: selenium/sessions:4.0.0
    container_name: selenium-sessions
    ports:
      - "5556:5556"
    depends_on:
      - selenium-event-bus
    env_file:
      - .env

  selenium-session-queue:
    image: selenium/session-queue:4.0.0
    container_name: selenium-session-queue
    ports:
      - "5559:5559"
    depends_on:
      - selenium-event-bus
    env_file:
      - .env

  selenium-distributor:
    image: selenium/distributor:4.0.0
    container_name: selenium-distributor
    ports:
      - "5553:5553"
    depends_on:
      - selenium-event-bus
      - selenium-sessions
      - selenium-session-queue
    env_file:
      - .env

  selenium-router:
    image: selenium/router:4.0.0
    container_name: selenium-router
    ports:
      - "4444:4444"
    depends_on:
      - selenium-distributor
      - selenium-sessions
      - selenium-session-queue
    env_file:
      - .env

  chrome:
    container_name: chrome
    extends: 
      file: ../docker-compose-shared-chrome-full-grid.yml
      service: shared-chrome
    ports:
      - ${CHROME_VNC_PORT}:5900
    depends_on:
      - selenium-event-bus    
    environment:
      SE_NODE_MAX_SESSIONS: 5

  chrome-1024x768:
    container_name: chrome-1024x768
    extends: 
      file: ../docker-compose-shared-chrome-full-grid.yml
      service: shared-chrome
    ports:
      - ${CHROME2_VNC_PORT}:5900
    depends_on:
      - selenium-event-bus
  
  edge:
    image: selenium/node-edge:95.0
    shm_size: 2gb
    depends_on:
      - selenium-event-bus
    ports:
      - "${EDGE_VNC_PORT}:5900"
    env_file:
      - .env

  firefox:
    image: selenium/node-firefox:94.0
    shm_size: 2gb
    depends_on:
      - selenium-event-bus
    ports:
      - "${FIREFOX_VNC_PORT}:5900"
    env_file:
      - .env

  # calculator:
  #   extends:
  #     file: ../deploy-calculator.yml
  #     service: calculator
  #   profiles: ["deploy-calculator"]   
 

    