# When executing docker run for an image that contains a browser please use the flag --shm-size=2g to use the host's shared memory.
# https://github.com/SeleniumHQ/docker-selenium

version: "3.8"
services:
  opera:
    hostname: ${GRID_URL_ADDRESS}
    image: selenium/standalone-opera:75.0
    shm_size: 2gb
    ports:
      - ${GRID_URL_PORT}:4444
      - ${VNC_PORT}:5900
      - ${NO_VNC_PORT}:7900
    networks:
      - ${NETWORK_NAME}  
    env_file:
      - .env
  calculator:
    extends:
      file: ../deploy-calculator.yml
      service: calculator
    env_file:
      - .env
    networks:
      - ${NETWORK_NAME}

  maven:
    extends:
      file: ../maven-test-calculator.yml
      service: maven
    env_file:
      - .env
    environment:
     BROWSER_DEFAULT: "opera"
    command: bash -c " sh selenium-agregator/scripts/run_browser_standalone.sh"
    depends_on:
     - calculator     
    networks:
      - ${NETWORK_NAME}    
    profiles: ["test-app"]          
networks:
  selenium-grid:
   name: ${NETWORK_NAME} 
