# When executing docker run for an image that contains a browser please use the flag --shm-size=2g to use the host's shared memory.
# https://github.com/SeleniumHQ/docker-selenium

services:
  browser:
    image: selenium/standalone-edge:4.18.1

  maven:
    environment:
      DEFAULT_BROWSER: "MicrosoftEdge"
 
 
