apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - env:
            - name: APP_URL_REMOTE
              value: http://app-calculadora:3000
            - name: REMOTE_URL
              value: http://selenium-router:4444
          image: jenkinsci/blueocean:1.25.3
          name: jenkins
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-data-pvc
            - mountPath: /root/.m2
              name: m3
      # restartPolicy: Always
      volumes:
        - name: jenkins-data-pvc
          persistentVolumeClaim:
            claimName: jenkins-data-pvc
        - name: m3
          persistentVolumeClaim:
            claimName: m3
status: {}
