version: "3.8"
services:
  hub:
    image: selenium/hub
    container_name: ${HUB_ADDRESS}
    ports:
      - "${HUB_PORT}:${HUB_PORT}"
      - "4442:4442"
      - "4443:4443"
    environment:
        GRID_MAX_SESSION: 16
        GRID_BROWSER_TIMEOUT: 300
        GRID_TIMEOUT: 300
        GRID_HUB_PORT: ${HUB_PORT}
    networks:
      - ${NAME_NETWORK}  
  opera:
    container_name: opera
    image: selenium/node-opera-debug:3.141.59
    ports:
      - ${NODE_OPERA_PORT}:5555
      - ${OPERA_VNC_PORT}:5900
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: ${HUB_ADDRESS}
      HUB_PORT_4444_TCP_PORT: ${HUB_PORT}
      VNC_NO_PASSWORD: "true" 
      NODE_MAX_INSTANCES: 1
    networks:
      - ${NAME_NETWORK}   
networks:
  selenium-grid:
   name: ${NAME_NETWORK} 
