services:
  hub:
    image: selenium/hub:4.18.1
    container_name: ${SELENIUM_ADDRESS}
    hostname: ${SELENIUM_ADDRESS}
    ports:
      - "4442:4442"
      - "4443:4443"
      - "${SELENIUM_PORT}:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 20s

  firefox:
    image: selenium/node-firefox:4.18.1
    depends_on:
      hub:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${FIREFOX_VNC_PORT}:5900"

  edge:
    image: selenium/node-edge:4.18.1
    depends_on:
      hub:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${EDGE_VNC_PORT}:5900"

  chrome:
    extends:
      file: ../docker-compose-shared-chrome.yml
      service: shared-chrome
    depends_on:
      hub:
        condition: service_healthy
    ports:
      - "${CHROME_VNC_PORT}:5900"
    env_file:
      - .env
    environment:
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

  chrome-1024x768:
    extends:
      file: ../docker-compose-shared-chrome.yml
      service: shared-chrome
    depends_on:
      hub:
        condition: service_healthy
    ports:
      - ${CHROME_1024x768_VNC_PORT}:5900
    environment:
      SCREEN_WIDTH: 1024
      SCREEN_HEIGHT: 768
      NODE_APPLICATION_NAME: chrome-1024x768
    env_file:
      - .env

  calculator:
    extends:
      file: ../docker-compose-shared-calculator.yml
      service: calculator

  maven:
    extends:
      file: ../docker-compose-shared-calculator.yml
      service: maven
    command: bash -c "sh /scripts/run_calculator_test.sh"
    depends_on:
      hub:
        condition: service_healthy
      calculator:
        condition: service_started

volumes:
  m2_repository:
    name: m2_repository
    external: true
